-- Migration 017: Add HS Code field to products table
-- This adds support for Harmonized System classification codes

-- Add HS code fields to products table
ALTER TABLE products 
ADD COLUMN hs_code VARCHAR(6),
ADD COLUMN hs_code_description TEXT,
ADD COLUMN hs_code_confidence INTEGER CHECK (hs_code_confidence >= 0 AND hs_code_confidence <= 100),
ADD COLUMN hs_code_generated_at TIMESTAMP WITH TIME ZONE;

-- Add index for HS code lookups
CREATE INDEX idx_products_hs_code ON products (hs_code) WHERE hs_code IS NOT NULL;

-- Add comment to document the feature
COMMENT ON COLUMN products.hs_code IS 'Harmonized System trade classification code (6 digits)';
COMMENT ON COLUMN products.hs_code_description IS 'Description of what the HS code classification covers';
COMMENT ON COLUMN products.hs_code_confidence IS 'AI confidence level in HS code classification (0-100)';
COMMENT ON COLUMN products.hs_code_generated_at IS 'Timestamp when HS code was generated by AI';