-- 034: Three defects an adversarial review of the ledger reproduced against real data.
--
-- All three were introduced by 027-030 in this same branch. They are recorded here rather than
-- edited into those files because two of them falsify claims those files make in prose, and a
-- migration that quietly rewrites the reasoning behind a shipped schema teaches nobody anything.

BEGIN;

-- 1. The ledger did not have a defined order ------------------------------------------------------
--
-- 027's header claims "`balance_after = previous + delta` holds by construction and the ledger
-- always replays". That is true of the arithmetic and false of the reading, because the only
-- ordering available was `created_at`, and `created_at` defaulted to `NOW()` — which in Postgres is
-- the *transaction* start time, identical for every row a transaction writes.
--
-- Receiving a purchase order writes two movements in one transaction: the arrival, then the damage
-- found on it. Both got the same timestamp, so the tiebreak fell to a random UUID. Reproduced on
-- demo data: a `po_receipt` of +60 to a balance of 63 sorted *after* the `damage` of -5 that
-- followed it, so the stock history drawer showed a most-recent movement claiming a balance of 63
-- when the balance was 58, and a replay summing deltas in the displayed order arrived at -2.
--
-- An identity column is the fix rather than a higher-resolution clock: `clock_timestamp()` would
-- have made collisions rarer without making the order defined, which is the worse failure — a bug
-- that survives testing and appears in production.

ALTER TABLE public.inventory_transactions
  ADD COLUMN IF NOT EXISTS sequence BIGINT GENERATED BY DEFAULT AS IDENTITY;

/*
 * Existing rows get a sequence consistent with the balances they already record.
 *
 * Across different timestamps `created_at` is authoritative. Within one — that is, within a group
 * of movements one transaction wrote — it says nothing, so the order is reconstructed from the
 * chain the balances themselves form: a movement Y follows X exactly when
 * `Y.balance_after - Y.delta = X.balance_after`.
 *
 * Sorting the collided rows by `balance_after` was tried first and is wrong. A purchase order
 * receipt of +60 onto a balance of 3 lands at 63, and the damage of -5 found on that delivery lands
 * at 58 — so the row that came *first* has the higher balance, and ascending order reverses them.
 * Balances also repeat within a product's history, so no sort on them is a total order at all.
 *
 * The immutability trigger refuses every UPDATE, which is the point of it, so it is switched off
 * for exactly this statement. Assigning a sequence is not rewriting history: it records the order
 * these rows already stand in and changes no reason, delta or balance. The trigger is back on
 * before the transaction commits, and the assertions below prove both — that nothing else moved,
 * and that the ledger now replays exactly to every balance it records.
 */
CREATE TEMP TABLE ledger_before ON COMMIT DROP AS
  SELECT id, reason, delta, balance_after, product_id, location_id FROM public.inventory_transactions;

ALTER TABLE public.inventory_transactions DISABLE TRIGGER trg_inventory_transactions_immutable;

WITH RECURSIVE chain AS (
  SELECT id, product_id, location_id, created_at, delta, balance_after,
         balance_after - delta AS prev_balance
    FROM public.inventory_transactions
),
walk AS (
  /* The head of each same-timestamp group: no other row in the group ends where this one starts. */
  SELECT c.id, c.product_id, c.location_id, c.created_at, c.balance_after, 0 AS pos
    FROM chain c
   WHERE NOT EXISTS (
     SELECT 1 FROM chain o
      WHERE o.product_id IS NOT DISTINCT FROM c.product_id
        AND o.location_id IS NOT DISTINCT FROM c.location_id
        AND o.created_at = c.created_at
        AND o.id <> c.id
        AND o.balance_after = c.prev_balance
   )
  UNION ALL
  SELECT c.id, c.product_id, c.location_id, c.created_at, c.balance_after, w.pos + 1
    FROM walk w
    JOIN chain c
      ON c.product_id IS NOT DISTINCT FROM w.product_id
     AND c.location_id IS NOT DISTINCT FROM w.location_id
     AND c.created_at = w.created_at
     AND c.id <> w.id
     AND c.prev_balance = w.balance_after
   /* A malformed chain cannot loop this forever. Groups are the handful of movements one
    * transaction writes, so anything past a few hundred is a cycle, not a history. */
   WHERE w.pos < 500
),
position AS (
  SELECT id, MIN(pos) AS pos FROM walk GROUP BY id
),
ordered AS (
  SELECT t.id,
         ROW_NUMBER() OVER (
           ORDER BY t.created_at,
                    t.product_id,
                    t.location_id,
                    COALESCE(p.pos, 0),
                    t.id
         ) AS seq
    FROM public.inventory_transactions t
    LEFT JOIN position p ON p.id = t.id
)
UPDATE public.inventory_transactions t
   SET sequence = ordered.seq
  FROM ordered
 WHERE t.id = ordered.id;

ALTER TABLE public.inventory_transactions ENABLE TRIGGER trg_inventory_transactions_immutable;

DO $$
DECLARE v_bad INTEGER;
BEGIN
  SELECT COUNT(*) INTO v_bad
    FROM public.inventory_transactions t
    JOIN ledger_before b ON b.id = t.id
   WHERE (t.reason, t.delta, t.balance_after, t.product_id, t.location_id)
      IS DISTINCT FROM (b.reason, b.delta, b.balance_after, b.product_id, b.location_id);
  IF v_bad > 0 THEN
    RAISE EXCEPTION 'sequence backfill altered % ledger rows', v_bad;
  END IF;

  SELECT COUNT(*) INTO v_bad FROM public.inventory_transactions WHERE sequence IS NULL;
  IF v_bad > 0 THEN
    RAISE EXCEPTION '% ledger rows have no sequence', v_bad;
  END IF;

  /* The claim 027 made and could not keep. It is an assertion now, so an ordering that does not
   * replay fails the deploy instead of reaching a merchant's stock history. */
  SELECT COUNT(*) INTO v_bad FROM (
    SELECT balance_after,
           SUM(delta) OVER (PARTITION BY product_id, location_id ORDER BY sequence
                            ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS replayed
      FROM public.inventory_transactions
  ) r WHERE r.balance_after <> r.replayed;
  IF v_bad > 0 THEN
    RAISE EXCEPTION 'ledger does not replay to its own balances in % rows', v_bad;
  END IF;
END $$;

-- Restart the identity above the backfilled values so new rows keep extending the same order.
SELECT setval(
  pg_get_serial_sequence('public.inventory_transactions', 'sequence'),
  GREATEST(COALESCE((SELECT MAX(sequence) FROM public.inventory_transactions), 0), 1)
);

CREATE INDEX IF NOT EXISTS inventory_transactions_product_sequence_idx
  ON public.inventory_transactions (product_id, location_id, sequence DESC);

COMMENT ON COLUMN public.inventory_transactions.sequence IS
  'The order movements happened in. Read this, never created_at: NOW() is transaction start time, '
  'so every movement written by one transaction shares a timestamp.';

-- 2. The projection lost updates across locations -------------------------------------------------
--
-- `project_stock_quantity` recomputed `SUM(on_hand)` in both the SET and the `IS DISTINCT FROM`
-- guard. Under READ COMMITTED a blocked UPDATE re-checks its WHERE clause against the new row
-- version, but a subquery inside that clause is still evaluated against the statement's original
-- snapshot. So two transactions moving stock at *different* locations for the same product both
-- computed the pre-existing total, the second found it "unchanged", and skipped its write.
--
-- Reproduced: 100 units at one location and 50 at another, -10 at each concurrently, leaving
-- `inventory_levels` summing to 130 and `products.stock_quantity` reading 140. Same-location
-- concurrency was already correct — the upsert in `post_inventory_movement` serialises it.
--
-- The fix is to take the product's row lock *before* computing, so the second transaction waits and
-- then re-reads. Applying a delta instead of recomputing the sum was tried first and is wrong here:
-- it composes correctly with a concurrent writer but breaks the cycle with
-- `translate_direct_stock_write`, which relies on the projection being idempotent to terminate. On
-- an INSERT the delta form adds the opening balance to a `stock_quantity` that already contains it,
-- so each pass doubles the number and the two triggers recurse until the stack runs out. The seed
-- catches it immediately, which is the only reason it is described here rather than shipped.
--
-- This adds no deadlock that was not already possible: the projection has always taken the product
-- row lock while holding the levels lock, so the cycle with `translate_direct_stock_write` (which
-- holds products, then takes levels) predates this change. `FOR UPDATE` moves the acquisition a few
-- microseconds earlier, and a detected deadlock surfaces as a 409 rather than as a wrong number.

CREATE OR REPLACE FUNCTION public.project_stock_quantity()
RETURNS TRIGGER AS $$
DECLARE
  v_product_id UUID;
  v_store_id UUID;
BEGIN
  v_product_id := COALESCE(NEW.product_id, OLD.product_id);
  v_store_id := COALESCE(NEW.store_id, OLD.store_id);

  /*
   * Serialise projections for this product. A concurrent mover at another location blocks here and
   * resumes with a new statement snapshot, so the SUM below sees their committed rows rather than
   * the ones its own statement started with.
   */
  PERFORM 1 FROM public.products
   WHERE id = v_product_id AND store_id = v_store_id
     FOR UPDATE;

  UPDATE public.products p
     SET stock_quantity = COALESCE((
           SELECT SUM(l.on_hand)::int
             FROM public.inventory_levels l
            WHERE l.product_id = v_product_id AND l.store_id = v_store_id
         ), 0),
         updated_at = NOW()
   WHERE p.id = v_product_id AND p.store_id = v_store_id
     -- Still the termination condition for the cycle with `translate_direct_stock_write`, and still
     -- what keeps a sync pass from churning `updated_at` across the whole catalogue.
     AND p.stock_quantity IS DISTINCT FROM COALESCE((
           SELECT SUM(l.on_hand)::int
             FROM public.inventory_levels l
            WHERE l.product_id = v_product_id AND l.store_id = v_store_id
         ), 0);

  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

-- Correct anything the old function already dropped.
UPDATE public.products p
   SET stock_quantity = COALESCE((
         SELECT SUM(l.on_hand)::int FROM public.inventory_levels l
          WHERE l.product_id = p.id AND l.store_id = p.store_id
       ), 0)
 WHERE p.track_inventory
   AND p.stock_quantity IS DISTINCT FROM COALESCE((
         SELECT SUM(l.on_hand)::int FROM public.inventory_levels l
          WHERE l.product_id = p.id AND l.store_id = p.store_id
       ), 0);

-- 3. Turning tracking on left the ledger permanently behind ---------------------------------------
--
-- `trg_translate_direct_stock_write` is guarded on `NEW.track_inventory`, which is correct — an
-- untracked product has no balance to keep — but nothing reconciled when a merchant later turned
-- tracking *on*. The product kept whatever `stock_quantity` it had accumulated while untracked and
-- gained no levels row, so the inventory grid reported "out of stock, 0 available" for a product
-- the catalogue and the storefront were selling with 50 in hand, and the ledger could not replay
-- to the number the cart checks against.
--
-- Reproduced entirely through public admin routes: create with `track_inventory: false` and
-- `stock_quantity: 50`, then `PUT /api/admin/inventory/{id} {"track_inventory": true}`.

CREATE OR REPLACE FUNCTION public.open_balance_on_tracking_enabled()
RETURNS TRIGGER AS $$
DECLARE
  v_current INTEGER;
  v_delta INTEGER;
BEGIN
  SELECT COALESCE(SUM(l.on_hand), 0) INTO v_current
    FROM public.inventory_levels l
   WHERE l.product_id = NEW.id AND l.store_id = NEW.store_id;

  v_delta := COALESCE(NEW.stock_quantity, 0) - v_current;

  IF v_delta <> 0 THEN
    PERFORM public.post_inventory_movement(
      p_store_id       => NEW.store_id,
      p_product_id     => NEW.id,
      p_delta          => v_delta,
      p_reason         => 'initial_stock'::inventory_reason,
      p_location_id    => NULL,
      p_reference_type => 'tracking_enabled',
      p_reference_id   => NULL,
      p_actor_user_id  => NULL,
      p_note           => 'Opening balance recorded when stock tracking was turned on'
    );
  END IF;

  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_open_balance_on_tracking_enabled ON public.products;
CREATE TRIGGER trg_open_balance_on_tracking_enabled
  AFTER UPDATE OF track_inventory ON public.products
  FOR EACH ROW
  WHEN (NEW.track_inventory AND NOT COALESCE(OLD.track_inventory, false))
  EXECUTE FUNCTION public.open_balance_on_tracking_enabled();

-- And reconcile any product already left in that state.
SELECT public.post_inventory_movement(
         p.store_id, p.id,
         (COALESCE(p.stock_quantity, 0) - COALESCE((
            SELECT SUM(l.on_hand)::int FROM public.inventory_levels l
             WHERE l.product_id = p.id AND l.store_id = p.store_id
          ), 0))::int,
         'initial_stock'::inventory_reason,
         NULL, 'tracking_enabled', NULL, NULL,
         'Opening balance recorded when stock tracking was turned on'
       )
  FROM public.products p
 WHERE p.track_inventory
   AND COALESCE(p.stock_quantity, 0) <> COALESCE((
         SELECT SUM(l.on_hand)::int FROM public.inventory_levels l
          WHERE l.product_id = p.id AND l.store_id = p.store_id
       ), 0);

INSERT INTO public.schema_migrations (version, description)
VALUES ('034', 'Ledger ordering, a lost-update in the stock projection, and opening a balance when tracking is enabled')
ON CONFLICT (version) DO NOTHING;

COMMIT;
