-- 038: `unavailable` was a column nothing ever wrote.
--
-- `inventory_levels.unavailable` participates in the generated `available` column, is selected by
-- the grid, exported in the CSV, shown on the product detail page and counted in a statistics tile
-- — and no code path in the application, the scripts or the database ever set it to anything but
-- zero. So "present but not saleable" was a concept the product displayed and did not have, and the
-- grid's "Unavailable" view could never match a row.
--
-- The gap it leaves is a real one. When a merchant finds a damaged case, the units are still on the
-- shelf; the questions "how many do I physically have" and "how many can I sell" have different
-- answers, and an inventory system that cannot hold them apart forces a choice between counting
-- stock that cannot be sold and destroying the record of stock that physically exists.
--
-- This adds holding, as its own movement, rather than changing what `damage` means. `damage` stays
-- what it has always been — units gone, written off on discovery — because rewriting the meaning of
-- a reason already recorded against historical rows would falsify the ledger this whole branch
-- exists to make trustworthy.

BEGIN;

ALTER TYPE inventory_reason ADD VALUE IF NOT EXISTS 'quarantine';
ALTER TYPE inventory_reason ADD VALUE IF NOT EXISTS 'release';

COMMIT;

BEGIN;

/*
 * Move units between sellable and held, without changing how many are physically present.
 *
 * A hold is not a stock movement: `on_hand` does not change, because nothing left the building. It
 * changes `unavailable`, and `available` — a generated column — follows.
 *
 * The ledger's `delta` is an on-hand delta and carries a `delta <> 0` check, so a hold cannot be
 * written as an ordinary movement. It gets its own table rather than a nullable column on the
 * ledger: `inventory_transactions` means "units moved", every row in it satisfies
 * `balance_after = previous + delta`, and admitting rows that break that to store a different kind
 * of fact would cost the one property that makes the ledger worth having.
 */
CREATE TABLE IF NOT EXISTS public.inventory_holds (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  store_id      UUID NOT NULL REFERENCES public.stores(id) ON DELETE CASCADE,
  product_id    UUID NOT NULL,
  location_id   UUID NOT NULL,
  sku           VARCHAR(255) NOT NULL,

  -- Positive holds units back; negative returns them to sale.
  delta         INTEGER NOT NULL CHECK (delta <> 0),
  -- Held units at this location after this row, the same invariant the ledger keeps.
  held_after    INTEGER NOT NULL CHECK (held_after >= 0),

  reason        inventory_reason NOT NULL,
  note          TEXT,
  actor_user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
  sequence      BIGINT GENERATED BY DEFAULT AS IDENTITY,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  FOREIGN KEY (product_id, store_id) REFERENCES public.products(id, store_id) ON DELETE CASCADE,
  FOREIGN KEY (location_id, store_id) REFERENCES public.inventory_locations(id, store_id)
);

CREATE INDEX IF NOT EXISTS inventory_holds_product_idx
  ON public.inventory_holds (product_id, location_id, sequence DESC);

COMMENT ON TABLE public.inventory_holds IS
  'Units physically present but not sellable — damaged, quarantined, awaiting inspection. Kept '
  'apart from inventory_transactions because a hold moves nothing: on_hand is unchanged.';

/**
 * Hold units back from sale, or release them.
 *
 * Refuses to hold more than is available, because holding stock that is already promised to a
 * customer would silently make an order unfulfillable without saying so.
 */
CREATE OR REPLACE FUNCTION public.post_inventory_hold(
  p_store_id      UUID,
  p_product_id    UUID,
  p_delta         INTEGER,
  p_reason        inventory_reason,
  p_location_id   UUID DEFAULT NULL,
  p_actor_user_id UUID DEFAULT NULL,
  p_note          TEXT DEFAULT NULL
) RETURNS public.inventory_holds AS $$
DECLARE
  v_location_id UUID;
  v_sku VARCHAR(255);
  v_level RECORD;
  v_row public.inventory_holds;
BEGIN
  IF p_delta = 0 THEN
    RAISE EXCEPTION 'A hold of zero units records nothing';
  END IF;

  SELECT sku INTO v_sku FROM public.products WHERE id = p_product_id AND store_id = p_store_id;
  IF v_sku IS NULL THEN
    RAISE EXCEPTION 'Product % is not in store %', p_product_id, p_store_id;
  END IF;

  v_location_id := COALESCE(
    p_location_id,
    (SELECT id FROM public.inventory_locations
      WHERE store_id = p_store_id AND is_default LIMIT 1)
  );
  IF v_location_id IS NULL THEN
    RAISE EXCEPTION 'Store % has no default inventory location', p_store_id;
  END IF;

  SELECT * INTO v_level FROM public.inventory_levels
   WHERE store_id = p_store_id AND product_id = p_product_id AND location_id = v_location_id
     FOR UPDATE;

  IF v_level IS NULL THEN
    RAISE EXCEPTION 'There is no stock of % at that location to hold', v_sku;
  END IF;

  IF p_delta > 0 AND p_delta > v_level.available THEN
    RAISE EXCEPTION
      'Only % units of % are available to hold at that location', v_level.available, v_sku;
  END IF;

  IF p_delta < 0 AND (-p_delta) > v_level.unavailable THEN
    RAISE EXCEPTION
      'Only % units of % are being held at that location', v_level.unavailable, v_sku;
  END IF;

  UPDATE public.inventory_levels
     SET unavailable = unavailable + p_delta,
         updated_at = NOW()
   WHERE store_id = p_store_id AND product_id = p_product_id AND location_id = v_location_id
   RETURNING * INTO v_level;

  INSERT INTO public.inventory_holds
    (store_id, product_id, location_id, sku, delta, held_after, reason, note, actor_user_id)
  VALUES
    (p_store_id, p_product_id, v_location_id, v_sku, p_delta, v_level.unavailable,
     p_reason, p_note, p_actor_user_id)
  RETURNING * INTO v_row;

  RETURN v_row;
END;
$$ LANGUAGE plpgsql;

/*
 * Holds are as append-only as movements, and for the same reason: the record of a case being
 * quarantined is evidence, and a system where it can be edited away answers nothing.
 */
CREATE OR REPLACE FUNCTION public.inventory_holds_are_immutable()
RETURNS TRIGGER AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    IF NOT EXISTS (SELECT 1 FROM public.products WHERE id = OLD.product_id) THEN
      RETURN OLD;
    END IF;
    RAISE EXCEPTION
      'inventory_holds is append-only; release the units instead of deleting hold %', OLD.id;
  END IF;

  RAISE EXCEPTION 'inventory_holds is append-only; post a release instead of an UPDATE';
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_inventory_holds_immutable ON public.inventory_holds;
CREATE TRIGGER trg_inventory_holds_immutable
  BEFORE UPDATE OR DELETE ON public.inventory_holds
  FOR EACH ROW EXECUTE FUNCTION public.inventory_holds_are_immutable();

INSERT INTO public.schema_migrations (version, description)
VALUES ('038', 'Quarantine: units present but not sellable, which the unavailable column advertised and nothing wrote')
ON CONFLICT (version) DO NOTHING;

COMMIT;
